(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this);function n(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
n("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,h){this.g=f;ba(this,"description",{configurable:!0,writable:!0,value:h})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
function q(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function la(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.G=b.prototype}var ma="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)Object.prototype.hasOwnProperty.call(d,e)&&(a[e]=d[e])}return a};
n("Object.assign",function(a){return a||ma});n("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});n("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
n("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==this.indexOf(b,c||0)}});n("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});var r=this||self;var na=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var oa,t;a:{for(var pa=["CLOSURE_FLAGS"],u=r,qa=0;qa<pa.length;qa++)if(u=u[pa[qa]],null==u){t=null;break a}t=u}var ra=t&&t[610401301];oa=null!=ra?ra:!1;var x,sa=r.navigator;x=sa?sa.userAgentData||null:null;function ta(a){return oa?x?x.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function z(a){var b;a:{if(b=r.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function A(){return oa?!!x&&0<x.brands.length:!1}function ua(){return A()?ta("Chromium"):(z("Chrome")||z("CriOS"))&&!(A()?0:z("Edge"))||z("Silk")};var va=A()?!1:z("Trident")||z("MSIE");function wa(a){a=void 0===a?document:a;return a.createElement("img")};function xa(a,b,c){var d=!1;d=void 0===d?!1:d;a.google_image_requests||(a.google_image_requests=[]);var e=wa(a.document);if(c){var f=function(){if(c){var h=a.google_image_requests,g=na(h,e);0<=g&&Array.prototype.splice.call(h,g,1)}e.removeEventListener&&e.removeEventListener("load",f,!1);e.removeEventListener&&e.removeEventListener("error",f,!1)};e.addEventListener&&e.addEventListener("load",f,!1);e.addEventListener&&e.addEventListener("error",f,!1)}d&&(e.attributionSrc="");e.src=b;a.google_image_requests.push(e)}
;!z("Android")||ua();ua();z("Safari")&&(ua()||(A()?0:z("Coast"))||(A()?0:z("Opera"))||(A()?0:z("Edge"))||(A()?ta("Microsoft Edge"):z("Edg/"))||A()&&ta("Opera"));var ya={},B=null;
function za(a){var b;void 0===b&&(b=0);if(!B){B={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));ya[e]=f;for(var h=0;h<f.length;h++){var g=f[h];void 0===B[g]&&(B[g]=h)}}}b=ya[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var k=a[f],l=a[f+1];g=a[f+2];h=b[k>>2];k=b[(k&3)<<4|l>>4];l=b[(l&15)<<2|g>>6];g=b[g&63];c[e++]=h+k+l+g}h=0;g=d;switch(a.length-f){case 2:h=
a[f+1],g=b[(h&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|h>>4]+g+d}return c.join("")};var Aa,Ba="undefined"!==typeof TextEncoder;var Ca="undefined"!==typeof Uint8Array,Da=!va&&"function"===typeof btoa;var C=0,D=0;function Ea(){this.g=[]}Ea.prototype.length=function(){return this.g.length};Ea.prototype.end=function(){var a=this.g;this.g=[];return a};function E(a,b){for(;127<b;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function Fa(a,b){if(0<=b)E(a,b);else{for(var c=0;9>c;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}function Ga(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)};function Ha(){this.j=[];this.i=0;this.g=new Ea}function F(a,b){0!==b.length&&(a.j.push(b),a.i+=b.length)};function G(a){this.g=a};function H(a){return Array.prototype.slice.call(a)};var I="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0,J=I?function(a,b){a[I]|=b}:function(a,b){void 0!==a.g?a.g|=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function Ia(a){var b=K(a);1!==(b&1)&&(Object.isFrozen(a)&&(a=H(a)),L(a,b|1))}
var Ja=I?function(a,b){a[I]&=~b}:function(a,b){void 0!==a.g&&(a.g&=~b)},K=I?function(a){return a[I]|0}:function(a){return a.g|0},N=I?function(a){return a[I]}:function(a){return a.g},L=I?function(a,b){a[I]=b}:function(a,b){void 0!==a.g?a.g=b:Object.defineProperties(a,{g:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function Ka(a,b){Object.isFrozen(a)&&(a=H(a));L(a,b);return a}function La(a){J(a,1);return a}function Ma(a,b){L(b,(a|0)&-99)}
function Na(a,b){L(b,(a|34)&-73);a&4&&Object.freeze(b)}function O(a){a=a>>10&1023;return 0===a?536870912:a};var Oa={};function P(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var Q,Pa=[];L(Pa,39);Q=Object.freeze(Pa);function Qa(a){if(a&2)throw Error();};function Ra(a){if("number"!==typeof a)throw Error();return a}function Sa(a){if(null==a)return a;if("string"===typeof a){if(!a)return;a=+a}return"number"===typeof a?a:void 0}function Ta(a){if(null!=a&&"string"!==typeof a)throw Error();return a};var Ua;function Va(a){switch(typeof a){case "number":return 0<a?void 0:[-a,void 0];case "string":return[0,a];case "object":return a}}
function R(a,b,c){null==a&&(a=Ua);Ua=void 0;if(null==a){var d=96;c?(a=[c],d|=512):a=[];b&&(d=d&-1047553|(b&1023)<<10)}else{if(!Array.isArray(a))throw Error();d=K(a);if(d&64)return a;d|=64;if(c&&(d|=512,c!==a[0]))throw Error();a:{c=a;var e=c.length;if(e){var f=e-1,h=c[f];if(P(h)){d|=256;b=(d>>9&1)-1;e=f-b;1024<=e&&(Wa(c,b,h),e=1023);d=d&-1047553|(e&1023)<<10;break a}}b&&(h=(d>>9&1)-1,b=Math.max(b,e-h),1024<b&&(Wa(c,h,{}),d|=256,b=1023),d=d&-1047553|(b&1023)<<10)}}L(a,d);return a}
function Wa(a,b,c){for(var d=1023+b,e=a.length,f=d;f<e;f++){var h=a[f];null!=h&&h!==c&&(c[f-b]=h)}a.length=d+1;a[d]=c};function Xa(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a&&!Array.isArray(a)&&Ca&&null!=a&&a instanceof Uint8Array){if(Da){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else a=za(a);return a}}return a};function Ya(a,b,c){a=H(a);var d=a.length,e=b&256?a[d-1]:void 0;d+=e?-1:0;for(b=b&512?1:0;b<d;b++)a[b]=c(a[b]);if(e){b=a[b]={};for(var f in e)b[f]=c(e[f])}return a}function Za(a,b,c,d,e,f){if(null!=a){if(Array.isArray(a))a=e&&0==a.length&&K(a)&1?void 0:f&&K(a)&2?a:ab(a,b,c,void 0!==d,e,f);else if(P(a)){var h={},g;for(g in a)h[g]=Za(a[g],b,c,d,e,f);a=h}else a=b(a,d);return a}}
function ab(a,b,c,d,e,f){var h=d||c?K(a):0;d=d?!!(h&32):void 0;a=H(a);for(var g=0;g<a.length;g++)a[g]=Za(a[g],b,c,d,e,f);c&&c(h,a);return a}function bb(a){return a.l===Oa?a.toJSON():Xa(a)};function cb(a,b,c){c=void 0===c?Na:c;if(null!=a){if(Ca&&a instanceof Uint8Array)return b?a:new Uint8Array(a);if(Array.isArray(a)){var d=K(a);return d&2?a:!b||d&68||!(d&32||0===d)?ab(a,cb,d&4?Na:c,!0,!1,!0):(L(a,d|34),a)}a.l===Oa&&(b=a.h,c=N(b),a=c&2?a:db(a,b,c,!0));return a}}function db(a,b,c,d){a=a.constructor;Ua=b=eb(b,c,d);b=new a(b);Ua=void 0;return b}function eb(a,b,c){var d=c||b&2?Na:Ma,e=!!(b&32);a=Ya(a,b,function(f){return cb(f,e,d)});J(a,32|(c?2:0));return a};function fb(a,b,c,d){if(-1===c)return null;if(c>=O(b)){if(b&256)return a[a.length-1][c]}else{var e=a.length;if(d&&b&256&&(d=a[e-1][c],null!=d))return d;b=c+((b>>9&1)-1);if(b<e)return a[b]}}function gb(a,b,c){a=a.h;var d=N(a);Qa(d);S(a,d,b,c)}function S(a,b,c,d,e){var f=O(b);if(c>=f||e){e=b;if(b&256)f=a[a.length-1];else{if(null==d)return;f=a[f+((b>>9&1)-1)]={};e|=256}f[c]=d;e!==b&&L(a,e)}else a[c+((b>>9&1)-1)]=d,b&256&&(a=a[a.length-1],c in a&&delete a[c])}
function T(a,b,c,d){a=a.h;var e=N(a);Qa(e);for(var f=0,h=0;h<c.length;h++){var g=c[h];null!=fb(a,e,g)&&(0!==f&&S(a,e,f),f=g)}(c=f)&&c!==b&&null!=d&&S(a,e,c);S(a,e,b,d)}
function hb(a,b,c,d,e,f){var h=!!(b&2);var g=b&2;var k=fb(a,b,d,e);Array.isArray(k)||(k=Q);var l=K(k);l&1||La(k);g?l&2||J(k,34):l&32&&!(l&2)&&Ja(k,32);g=k;if(g===Q||!(K(g)&4)){l=g;g=!!(b&2);k=!!(K(l)&2);h=l;!g&&k&&(l=H(l));var m=b|(k?2:0);k=k||void 0;for(var w=0,v=0;w<l.length;w++){var p=l[w];var $a=c,M=!1;if(null==p||"object"!==typeof p||(M=Array.isArray(p))||p.l!==Oa)if(M){var y=M=K(p);0===y&&(y|=m&32);y|=m&2;y!==M&&L(p,y);p=new $a(p)}else p=void 0;void 0!==p&&(k=k||N(p.h)&2,l[v++]=p)}v<w&&(l.length=
v);c=l;l=K(c);m=l|5;k=k?m&-9:m|8;l!=k&&(c=Ka(c,k));l=c;h!==l&&S(a,b,d,l,e);(g&&2!==f||1===f)&&Object.freeze(l);return l}if(3===f)return g;h?2===f&&(f=K(g),g=H(g),L(g,f),S(a,b,d,g,e)):(c=Object.isFrozen(g),1===f?c||Object.freeze(g):(f=K(g),h=f&-35,c&&(g=H(g),f=0,S(a,b,d,g,e)),f!==h&&L(g,h)));return g}function ib(a,b){var c=a.h,d=N(c);a=!!(d&2);b=hb(c,d,jb,b,void 0,a?1:2);if(!(a||K(b)&8)){for(a=0;a<b.length;a++){c=b[a];d=c.h;var e=N(d);d=e&2?db(c,d,e,!1):c;c!==d&&(b[a]=d)}J(b,8)}return b}
function kb(a,b,c){var d=a.h,e=N(d);Qa(e);if(null!=c){for(var f=!!c.length,h=0;h<c.length;h++){var g=c[h];f=f&&!(K(g.h)&2)}h=K(c);g=h|1;g=(f?g|8:g&-9)|4;g!=h&&(c=Ka(c,g))}null==c&&(c=void 0);S(d,e,b,c);return a};function U(a,b,c){this.h=R(a,b,c)}U.prototype.toJSON=function(){var a=ab(this.h,bb,void 0,void 0,!1,!1);return lb(this,a,!0)};U.prototype.l=Oa;U.prototype.toString=function(){return lb(this,this.h,!1).toString()};
function lb(a,b,c){var d=a.constructor.u,e=O(N(c?a.h:b)),f=!1;if(d){if(!c){b=H(b);var h;if(b.length&&P(h=b[b.length-1]))for(f=0;f<d.length;f++)if(d[f]>=e){Object.assign(b[b.length-1]={},h);break}f=!0}e=b;c=!c;h=N(a.h);a=O(h);h=(h>>9&1)-1;for(var g,k,l=0;l<d.length;l++)if(k=d[l],k<a){k+=h;var m=e[k];null==m?e[k]=c?Q:La([]):c&&m!==Q&&Ia(m)}else g||(m=void 0,e.length&&P(m=e[e.length-1])?g=m:e.push(g={})),m=g[k],null==g[k]?g[k]=c?Q:La([]):c&&m!==Q&&Ia(m)}d=b.length;if(!d)return b;var w;if(P(g=b[d-1])){a:{var v=
g;e={};c=!1;for(var p in v)a=v[p],Array.isArray(a)&&a!=a&&(c=!0),null!=a?e[p]=a:c=!0;if(c){for(var $a in e){v=e;break a}v=null}}v!=g&&(w=!0);d--}for(;0<d;d--){g=b[d-1];if(null!=g)break;var M=!0}if(!w&&!M)return b;var y;f?y=b:y=Array.prototype.slice.call(b,0,d);b=y;f&&(b.length=d);v&&b.push(v);return b};function mb(a,b){var c=a[b];"function"==typeof c&&(c=c(),a[b]=c);(a=Array.isArray(c))&&!(a=nb in c||ob in c)&&(a=0<c.length)&&(a=c[0],b=Va(a),null!=b&&b!==a&&(c[0]=b),a=null!=b);return a?c:void 0}var pb=Symbol();function qb(a){var b=a[pb];if(!b){var c=rb(a);b=function(d,e){return sb(d,e,c)};a[pb]=b}return b}var ob=Symbol();function tb(a){return a.g}function ub(a,b){var c,d,e=a.g;return function(f,h,g){return e(f,h,g,d||(d=rb(b).i),c||(c=qb(b)))}}
function rb(a){var b=a[ob];if(b)return b;a:{b=a[ob]={};var c=tb,d=ub;b.i=Va(a[0]);var e=1;if(a.length>e&&"number"!==typeof a[e]){var f=a[e++];if(Array.isArray(f)){b.j=f[0];b.g=f[1];break a}b.g=f}for(f=0;e<a.length;){f+=a[e++];for(var h=e+1;h<a.length&&"number"!==typeof a[h];)h++;var g=a[e++];h-=e;switch(h){case 0:b[f]=c(g);break;case 1:(h=mb(a,e))?(e++,b[f]=d(g,h)):b[f]=c(g,a[e++]);break;case 2:h=b;var k=f;var l=e++;l=mb(a,l);h[k]=d(g,l,a[e++]);break;default:throw Error("unexpected number of binary field arguments: "+
h);}}}nb in a&&ob in a&&(a.length=0);return b}var nb=Symbol();function vb(a,b){var c=a[b];if(c)return c;if(c=a.g)if(c=c[b]){var d=c.D,e=c.F.g;if(d){var f=qb(d),h=rb(d).i;c=function(g,k,l){return e(g,k,l,h,f)}}else c=e;return a[b]=c}}function sb(a,b,c){for(var d=N(a),e=(d>>9&1)-1,f=a.length,h=f+(d&256?-1:0),g=d&512?1:0;g<h;g++){var k=a[g];if(null!=k){var l=g-e,m=vb(c,l);m&&m(b,k,l)}}if(d&256){a=a[f-1];for(var w in a)d=+w,Number.isNaN(d)||(e=a[w],null!=e&&(f=vb(c,d))&&f(b,e,d))}}
function wb(a,b,c){b=null==b||"string"===typeof b?b:void 0;if(null!=b){var d=!1;d=void 0===d?!1:d;if(Ba){if(d&&/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(b))throw Error("Found an unpaired surrogate");b=(Aa||(Aa=new TextEncoder)).encode(b)}else{for(var e=0,f=new Uint8Array(3*b.length),h=0;h<b.length;h++){var g=b.charCodeAt(h);if(128>g)f[e++]=g;else{if(2048>g)f[e++]=g>>6|192;else{if(55296<=g&&57343>=g){if(56319>=g&&h<b.length){var k=b.charCodeAt(++h);if(56320<=k&&
57343>=k){g=1024*(g-55296)+k-56320+65536;f[e++]=g>>18|240;f[e++]=g>>12&63|128;f[e++]=g>>6&63|128;f[e++]=g&63|128;continue}else h--}if(d)throw Error("Found an unpaired surrogate");g=65533}f[e++]=g>>12|224;f[e++]=g>>6&63|128}f[e++]=g&63|128}}b=e===f.length?f:f.subarray(0,e)}E(a.g,8*c+2);E(a.g,b.length);F(a,a.g.end());F(a,b)}}
var xb=new G(function(a,b,c){b=null==b?b:"number"===typeof b||"NaN"===b||"Infinity"===b||"-Infinity"===b?Number(b):void 0;if(null!=b){E(a.g,8*c+1);a=a.g;var d=+b;if(0===d)D=0<1/d?0:2147483648,C=0;else if(isNaN(d))D=2147483647,C=4294967295;else if(d=(c=0>d?-2147483648:0)?-d:d,1.7976931348623157E308<d)D=(c|2146435072)>>>0,C=0;else if(2.2250738585072014E-308>d)b=d/Math.pow(2,-1074),D=(c|b/4294967296)>>>0,C=b>>>0;else{var e=d;b=0;if(2<=e)for(;2<=e&&1023>b;)b++,e/=2;else for(;1>e&&-1022<b;)e*=2,b--;d*=
Math.pow(2,-b);D=(c|b+1023<<20|1048576*d&1048575)>>>0;C=4503599627370496*d>>>0}Ga(a,C);Ga(a,D)}}),yb=new G(function(a,b,c){b=Sa(b);null!=b&&null!=b&&(E(a.g,8*c),Fa(a.g,b))}),zb=new G(wb),Ab=new G(wb),Bb=new G(function(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++){var h=a,g=b[f],k=c,l=e;g=g instanceof U?g.h:Array.isArray(g)?R(g,d[0],d[1]):void 0;if(null!=g){var m=h;E(m.g,8*k+2);k=m.g.end();F(m,k);k.push(m.i);l(g,h);l=k;g=l.pop();for(g=h.i+h.g.length()-g;127<g;)l.push(g&127|128),g>>>=7,
h.i++;l.push(g);h.i++}}}),Cb=new G(function(a,b,c){b=Sa(b);null!=b&&(b=parseInt(b,10),E(a.g,8*c),Fa(a.g,b))});function jb(a){this.h=R(a)}la(jb,U);var V=[1,2,3],Db=[4,5],Eb=[0,1,Cb,V,1,Cb,V,1,Ab,V,1,xb,Db,1,Ab,Db,1,yb];function Fb(a){this.h=R(a)}la(Fb,U);Fb.u=[1];Fb.prototype.g=function(a){return function(){var b=new Ha;sb(this.h,b,rb(a));F(b,b.g.end());for(var c=new Uint8Array(b.i),d=b.j,e=d.length,f=0,h=0;h<e;h++){var g=d[h];c.set(g,f);f+=g.length}b.j=[c];return c}}([0,1,Bb,Eb,1,zb,1,yb,1,zb,1,yb]);function Gb(a){this.h=R(a)}la(Gb,U);Gb.prototype.setData=function(a,b){var c=jb,d=this.h,e=N(d);Qa(e);d=hb(d,e,c,2,!1,2);b=null!=b?b:new c;if("number"!==typeof a||0>a||a>d.length)throw Error();void 0!=a?d.splice(a,1,b):d.push(b);K(b.h)&2&&Ja(d,8);return this};Gb.u=[1,2];function Hb(a){this.i=a;this.data=[];this.g=[]}Hb.prototype.setData=function(a,b,c){this.i.includes(c)&&this.data.push({key:a,value:b,channel:c})};function Ib(a){return a.data.some(function(b){return 1===b.channel})}Hb.prototype.setAttribute=function(a,b){this.g.push({key:a,value:b})};
function Jb(a,b,c,d){var e=new jb;"string"===typeof a?T(e,3,V,Ta(a)):d?T(e,1,V,a):T(e,2,V,a);if("number"===typeof b){if(null!=b&&"number"!==typeof b)throw Error("Value of float/double field must be a number|null|undefined, found "+typeof b+": "+b);T(e,4,Db,b)}else T(e,5,Db,Ta(b));c&&gb(e,6,null==c?c:Ra(c));return e};function W(){this.g=new Hb([]);this.A=Date.now();this.i=[];this.s=this.m=!1;this.o=100}
W.prototype.init=function(a,b,c,d,e,f){var h=this;this.g=new Hb(b);this.C=a;this.v=e;this.B=c;if(d){b=a=NaN;d=q(d);for(c=d.next();!c.done;c=d.next())e=q(c.value),c=e.next().value,e=e.next().value,6===c?a=Number(e):5===c?b=Number(e):this.g.setAttribute(c,e);!isNaN(a)&&0<=a?this.o=a:isNaN(b)||(this.m=!0,setInterval(this.j.bind(this),b),setTimeout(function(){Kb(h,"timeout")},3E5),document.addEventListener("visibilitychange",function(){"hidden"===document.visibilityState&&Kb(h,"document_hidden")}),window.addEventListener("beforeunload",
function(){Kb(h,"beforeunload")}))}if(f){f=q(f);for(a=f.next();!a.done;a=f.next())d=q(a.value),a=d.next().value,b=d.next().value,d=d.next().value,this.setData(a,b,d);"complete"===document.readyState?this.send():window.addEventListener("load",function(){h.send()})}};W.prototype.getBaseTime=function(){return this.A};W.prototype.setData=function(a,b,c){this.g.setData(a,b,c);this.i[c]?this.i[c]++:this.i[c]=1};W.prototype.setAttribute=function(a,b){this.g.setAttribute(a,b)};
W.prototype.send=function(a){var b=this;if(!this.m){var c=Ib(this.g)?0:this.o;a=null!=a?a:c;0<a?setTimeout(function(){return void b.j()},a):this.j()}};
W.prototype.j=function(){if(0<this.g.data.length){var a=this.C,b=this.v,c=this.B,d=this.g,e=[];var f=q(d.g);for(var h=f.next();!h.done;h=f.next())h=h.value,e.push(Jb(h.key,h.value,void 0,!0));f=[];d=q(d.data);for(h=d.next();!h.done;h=d.next())h=h.value,f.push(Jb(h.key,h.value,h.channel,!1));d=new Gb;e=kb(d,1,e);f=kb(e,2,f);e=new Fb;f=ib(f,1).concat(ib(f,2));e=kb(e,1,f);a&&gb(e,2,Ta(a));c&&gb(e,4,Ta(c));b&&gb(e,5,null==b?b:Ra(b));a="https://pagead2.googlesyndication.com/pagead/gen_204?id=mys&d="+za(e.g()).replace(/\//g,
"_").replace(/\+/g,"-");b=window;var g=void 0===g?!1:g;if(c=b.navigator)c=b.navigator.userAgent,c=/Chrome/.test(c)&&!/Edge/.test(c)?!0:!1;c&&b.navigator.sendBeacon?b.navigator.sendBeacon(a):xa(b,a,void 0===g?!1:g);this.g.data=[]}};function Kb(a,b){a.s||(a.g.setData(32,b,4),a.i.forEach(function(c,d){a.g.setData(31,c,d)}),a.j(),a.s=!0)}
if(!window.mys||!window.mys.pingback){var Lb=new W,X=["mys","pingback"],Y=r;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===Lb?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Lb};}).call(this);
