(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f=this||self;var g,h;a:{for(var k=["CLOSURE_FLAGS"],l=f,r=0;r<k.length;r++)if(l=l[k[r]],null==l){h=null;break a}h=l}var t=h&&h[610401301];g=null!=t?t:!1;var u;const v=f.navigator;u=v?v.userAgentData||null:null;function w(a){return g?u?u.brands.some(({brand:b})=>b&&-1!=b.indexOf(a)):!1:!1}function x(a){var b;a:{if(b=f.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function y(){return g?!!u&&0<u.brands.length:!1}function z(){return y()?w("Chromium"):(x("Chrome")||x("CriOS"))&&!(y()?0:x("Edge"))||x("Silk")};!x("Android")||z();z();x("Safari")&&(z()||(y()?0:x("Coast"))||(y()?0:x("Opera"))||(y()?0:x("Edge"))||(y()?w("Microsoft Edge"):x("Edg/"))||y()&&w("Opera"));function A(a){let b;null==(b=window.AFMA_Communicator)||b.addEventListener("onshow",a)};var B=class{constructor(){this.channel=4;(this.g=!(!window.mys||!window.mys.pingback))&&this.setData(43,Date.now()-window.mys.pingback.getBaseTime())}setAttribute(a,b){this.g&&window.mys.pingback.setAttribute(a,b)}setData(a,b){this.g&&window.mys.pingback.setData(a,b,this.channel)}send(a){this.g&&window.mys.pingback.send(a)}};const C=["googqscp","osdlfm"];
function D(a,b){var d;if((a.g.includes(b)||a.i.includes(b))&&(null==(d=window.performance)?0:d.getEntries)&&window.PerformanceNavigationTiming&&window.PerformanceResourceTiming){d=a.g.includes(b)?["script"]:[];var c=window.performance.getEntries(),e=0,n=0,m=0,p=0;for(const q of c)if(!q.name.includes("pagead2.googlesyndication.com/pagead/gen_204?id=mys"))if(q instanceof window.PerformanceNavigationTiming)e+=q.transferSize||0;else if(q instanceof window.PerformanceResourceTiming){c=q.initiatorType;
const F=q.transferSize||0;if(0===d.length||d.includes(c))m++,n+=0===F?1:0,p+=F}a.g.includes(b)?(a.pingback.setData(16,e),a.pingback.setData(17,p),a.pingback.setData(18,m),a.pingback.setData(19,n)):a.i.includes(b)&&(a.pingback.setData(20,p),a.pingback.setData(21,m),a.pingback.setData(22,n))}a.pingback.setData(b,window.performance.now());26===b&&E(a);a.pingback.send()}function G(a,b){a.h[b]=window.performance.now()}
function H(a,b){a.h.hasOwnProperty(b)&&(a.pingback.setData(b,window.performance.now()-a.h[b]),13===b&&E(a),a.pingback.send())}function E(a){a.pingback.setData(30,`${window.innerWidth}x${window.innerHeight}`);const {clientWidth:b,clientHeight:d}=a.context.body;a.pingback.setData(25,`${b}x${d}`)}
var J=class{constructor(){this.context=I;this.pingback=new B;this.h={};this.j={overallStart:()=>void D(this,3),overallReady:()=>void D(this,4),overallQuiet:()=>void D(this,5),overallError:()=>void D(this,6),assembleStart:()=>void G(this,7),assembleReady:()=>void H(this,7),decorateStart:()=>void G(this,8),decorateReady:()=>void H(this,8),fontStart:()=>void G(this,9),fontReady:()=>void H(this,9),spanStart:()=>void G(this,10),spanReady:()=>void H(this,10),prepareStart:()=>void G(this,11),prepareReady:()=>
void H(this,11),bindingStart:()=>void G(this,12),bindingReady:()=>void H(this,12),browserStart:()=>void G(this,13),browserStartEnd:()=>void H(this,13),browserReady:()=>void G(this,14),browserReadyEnd:()=>void H(this,14),browserQuiet:()=>void G(this,15),browserQuietEnd:()=>void H(this,15)};this.g=[23];this.i=[24]}};function K(a,b){a=a.getElementsByTagName("META");for(let d=0;d<a.length;++d)if(a[d].getAttribute("name")===b)return a[d].getAttribute("content")||"";return""};var M=class{constructor(){var a=L;this.body=a;this.g=[];K(a,"sampling_mod");var b=K(a,"namespace");if(!b){b="ns-"+(0,Math.random)().toString(36).substr(2,5);a:{var d=a.getElementsByTagName("META");for(let c=0;c<d.length;++c)if("namespace"===d[c].getAttribute("name")&&d[c].getAttribute("index")===(0).toString()){d[c].setAttribute("content",b);break a}d=a.querySelector("#mys-meta");d||(d=document.createElement("div"),d.id="mys-meta",d.style.position="absolute",d.style.display="none",a.appendChild(d));
a=document.createElement("META");a.setAttribute("name","namespace");a.setAttribute("content",b);a.setAttribute("index",(0).toString());d.appendChild(a)}}if(!(0<this.g.length)){a=K(this.body,"environment");for(const c of a.split("|"))c&&this.g.push(c)}}addEventListener(a,b){this.body.addEventListener(a,b)}};const L=document.getElementById("mys-content"),I=new M;
(function(){var a=new J,b;if(null!=(b=window.mys)&&b.pingback){b=a.context.body;window.addEventListener("error",c=>{var e=c.message||"";let n=!1;for(let m=0;m<C.length;++m){const p=C[m];if(e.includes(p)){e=p;n=!0;break}}e=c.type+": "+e;!n&&c.lineno&&c.colno&&(e+=` at ${c.lineno}:${c.colno}`);a.pingback.setData(1,e);a.pingback.send()});b.addEventListener("customError",c=>{let e="custom_error: ";c.detail&&(e+=c.detail.message);a.pingback.setData(2,e);a.pingback.send()});window.addEventListener("click",
c=>{const e=Date.now()-window.mys.pingback.getBaseTime();a.pingback.setData(47,`${c.clientX}x${c.clientY}@${e}`);a.pingback.send()},!0);var d;if(null!=(d=window.performance)&&d.now){window.addEventListener("DOMContentLoaded",()=>void D(a,23));window.addEventListener("load",()=>{D(a,24);setTimeout(()=>{var c;null!=(c=window.performance)&&c.getEntriesByType&&(c=performance.getEntriesByType("navigation")[0])&&(a.pingback.setData(50,c.fetchStart),a.pingback.setData(51,c.domainLookupStart),a.pingback.setData(52,
c.domainLookupEnd),a.pingback.setData(53,c.connectStart),a.pingback.setData(54,c.connectEnd),a.pingback.setData(55,c.secureConnectionStart),a.pingback.setData(56,c.requestStart),a.pingback.setData(57,c.responseStart),a.pingback.setData(58,c.responseEnd),a.pingback.setData(59,c.domInteractive),a.pingback.setData(60,c.domContentLoadedEventStart),a.pingback.setData(61,c.domContentLoadedEventEnd),a.pingback.setData(62,c.domComplete),a.pingback.setData(63,c.loadEventStart),a.pingback.setData(64,c.loadEventEnd),
a.pingback.send())},0)});A(()=>void D(a,26));for(const [c,e]of Object.entries(a.j))b.addEventListener(c,e)}}})();}).call(this);
