/* 1. write a javascript program to generate a random number and store it in
 a variable. The program them takes an input from the user to teell them whether 
 the guess was correct, greater or lesser than 100-(n of guesses) is the
 score of ther user. The program is expected to terminate once  the number
 is gussed. Number should be between 1-100.
*/

// let my_num = 67;
// function getRandom(num) {
//     let my_num = Math.floor(Math.random * num);
//     return my_num;
// };
// let number = 0;
// do {
//     number = prompt("Enter correct number");
// } while (my_num !== 0);
// console.log(number);

// let n = arr3.map((num) => {
//     return 100 - num;
// })
// console.log(n);


// let a = Math.random() * 100;
// a = Number.parseInt(a);
// let inp;
// let score = 100;

// while (inp != a) {
//     score = score - 1;
//     inp = prompt("En2ter the number :");
//     if (inp == a) {
//         console.log("Congratulation! You guess the correct number.");
//         console.log(`You guess the actual number in ${100 - score} chances`);
//     }
//     else if (inp > 1 && inp < 100) {
//         console.log("Your number is greater then the actual number.");
//     }
//     else if (inp < a && inp > 0) {
//         console.log("Your number is samaller then the actual number.");
//     }
//     else {
//         console.log("Enter number between 1 to 100");
//     }
// }


// 2.
// program where the user has to guess a number generated by a program

function guessNumber() {

    // generating a random integer from 1 to 10
    const random = Math.floor(Math.random() * 10) + 1;

    // take input from the user
    let number = parseInt(prompt('Guess a number from 1 to 10: '));

    // take the input until the guess is correct
    while (number !== random) {
        number = parseInt(prompt('Guess a number from 1 to 10: '));
    }

    // check if the guess is correct
    if (number == random) {
        console.log('You guessed the correct number.');
    }

}

// call the function
guessNumber();